INSERT INTO public.artista (nome, tipo) VALUES
('Serj Tankian', 'SOLO'),
('Mike Shinoda', 'SOLO'),
('Michel Teló', 'SOLO'),
('Ed Sheeran', 'SOLO'),
('Adele', 'SOLO'),
('Taylor Swift', 'SOLO'),
('Linkin Park', 'BANDA'),
('Imagine Dragons', 'BANDA'),
('Coldplay', 'BANDA'),
('Metallica', 'BANDA'),
('Queen', 'BANDA'),
('Foo Fighters', 'BANDA'),
('Maroon 5', 'BANDA'),
('Red Hot Chili Peppers', 'BANDA'),
('Beyoncé', 'SOLO'),
('Shakira', 'SOLO'),
('Bruno Mars', 'SOLO'),
('Green Day', 'BANDA'),
('The Beatles', 'BANDA'),
('U2', 'BANDA');
